### ISSUE TITLE
CSS实现带边框的三角形

### ISSUE THREAD

**Issue by Hyrmm** [Hyrmm/Blog#1]
### 1、css实现三角形的原理

> 在CSS盒子模型中，当一个盒子的两条边在边角处相交时，浏览器就会在交点处按照某个角度（如果盒子为正方形，则为顺时针45°、135°、225°、315°）绘制一条接合线。

```html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"><head>
<title></title>
<style type="text/css">
	#box{
		width: 30px;height : 30px;
		border-width: 20px;border-style:solid;
		border-color:red green blue orange;
    	}
</style>
</head><body>
<div id="box"></div></body>
</html>

```

<img src="http://hyrm.gitee.io/block/img/20210408001.png" alt="20210408" style="zoom:200%;" />

> 在这个例子中，我们为每一条边框定义不同的颜色（border color），并且设置足够大的宽度（border-width），然后可以很明显地看出两条边相交时的效果。如果我们把盒子的宽度（width）和高度（height）都定义为0时，以下效果

<img src="http://hyrm.gitee.io/block/img/20210408002.png" style="zoom:200%;" />

> 所以想生成一个三角形只要将border的三个其他方向的颜色调成透明即可得到一个三角形

```css
#box{
	width: 30px;height : 30px;
	border-width: 20px;border-style:solid;
	border-color:red green blue orange;
}
```

<img src="http://hyrm.gitee.io/block/img/20210408003.png" style="zoom:200%;" />

### 2、带边框的三级的实现原理

> 对于这种带边框的三角形，我们一般使用两个三角形来实现。一个作为背景色（内层三角形），一个作为边框色（外层三角形），然后通过定位布局重叠在一起。注意，两个三角形定位要相差1像素。一般情况下，都是将内层三角形相对于外层三角形进行定位，偏移1像素。
>
> 在实现带边框的三角形原理中，有一个关于绝对定位的问题是一定不可忽视的：上、右、下、左四个方向三角形相对于父元素定位是不同的。必须把这个问题理解清楚，我们才能深刻理解带边框三角形的实现原理

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        .triangle,
        .triangle div {
            width: 0;
            height: 0;
        }

        .triangle {
            border-width: 50px;
            border-style: solid;
            border-color: transparent transparent red transparent;

        }

        .triangle div {
            border-width: 50px;
            border-style: solid;
            border-color: green yellow blue brown;
        }
    </style>
</head>
<body>
    <div class="triangle">
        <div></div>
    </div>
</body>
</html>
```

<img src="http://hyrm.gitee.io/block/img/20210408004.png" style="zoom: 150%;" />

> 我们发现一个很奇怪的问题,为什么内部的蓝色三角形在这个位置？因为的他的父元素外部三角形的内容区`content`的高度和宽度都为0，所以内部三角形所对齐位置应该在外部三角行的中心部分，一张图解释下。

![](http://hyrm.gitee.io/block/img/20210408005.png)

> 接下来就开始利用定位和内部三角形和外部三角形的高度差,为外部三角形定制一个边框

```css
    <style>
        .triangle,
        .triangle div {
            width: 0;
            height: 0;
        }

        .triangle {
            /* 这里父元素定位,放置内三角形飘走 */
            position: relative;
            border-width: 30px;
            border-style: solid;
            border-color: transparent transparent red transparent;

        }

        .triangle div {
            position:absolute;
            top: -28px;
            left: -29px;
            border-width: 29px;
            border-style: solid;
            border-color: transparent transparent blue transparent;
        }
    </style>
```

![](http://hyrm.gitee.io/block/img/20210408006.png)

> 关于为什么 `top:-28px;` 和 `left:-29px:` 说可以尝试将外部三角的其他边框颜色显示出来,在进行调整,你就发现其中的道理

- author:hyrm

- dateTime:2021-04-08

- aside:发现最近心情有点郁闷,太过于学习而忘记了放松?
